title: Soroush Bassam
logo: "/images/logo_sb.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with experience in the entire data science lifecycle, including ETL, 
  data engineering, machine learning, optimization, and visualization.  
  <br><br>
  Skilled in SQL and Python (Pandas, Numpy, Scikit-learn, Matplotlib). 
  Focused on implementing efficient and scalable machine learning systems capable of identifying patterns in structured and unstructured data.
  <br><br>
  <a href="https://www.linkedin.com/in/soroushb/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-161438197-1
