# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Soroush Bassam
title: Machine Learning/Data Science
email: soroush.bassam@gmail.com
website: sbassam.github.io

# Social links
# twitter_username: facespics
github_username:  sbassam
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: soroushb
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Soroush and I'm a database developer with a passion for machine learning. I am also a part-time student working toward an MS in Computer Science.

  I am most skilled in: <mark>SQL</mark>, <mark>Python</mark> (<mark>Pandas</mark>, <mark>Numpy</mark>, <mark>scikit-learn</mark>, <mark>Matplotlib</mark>, <mark>PyTorch</mark>)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
